version: '3.8'

services:
  nomnom-gallery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nomnom-gallery
    restart: unless-stopped
    ports:
      - "3003:80"  # Change the first number if you want to use a different port
    environment:
      - NODE_ENV=production
      - REACT_APP_SPREADSHEET_URL=${SPREADSHEET_URL}  # Make sure to set this in Portainer
    networks:
      - nomnom-network

networks:
  nomnom-network:
    driver: bridge 